runtime: nodejs14

instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'strapi'
  DATABASE_USERNAME: 'postgres'
  DATABASE_PASSWORD: 'E5qzF1x0oBktdvCz'
  INSTANCE_CONNECTION_NAME: 'ethanmerrillwebsite:us-east4:ethan-website-postgresql'

beta_settings:
  cloud_sql_instances: 'ethanmerrillwebsite:us-east4:ethan-website-postgresql'